name: CSS linter

on:
  workflow_dispatch:
  push:
    paths: [ '**.css' ]
  pull_request:
    paths: [ '**.css' ]

jobs:
  Stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Stylelint
        run:  npm install stylelint stylelint-less stylelint-config-standard-less
      - name: Run Stylelint on .css files
        run:  npx stylelint "**/*.css"
